### ISSUE TITLE
Failing to run main because of SQLEngine

### ISSUE THREAD

**Issue by hatityechindove** [dropbox/securitybot#16]
I would like to get some assistance with a small issue I am facing (not strong in python). I have tried using `pip install SQLEngine` and even went on to install `SQLAlchemy` but I can't seem to go past this stage when I run `python main.py`

Can you please help

`└> python2.7 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from securitybot.bot import SecurityBot
  File "/Users/pathXXXX/securitybot/securitybot/bot.py", line 9, in <module>
    from securitybot.user import User
  File "/Users/pathXXXX/securitybot/securitybot/user.py", line 11, in <module>
    import securitybot.ignored_alerts as ignored_alerts
  File "/Users/pathXXXX/securitybot/securitybot/ignored_alerts.py", line 6, in <module>
    from securitybot.sql import SQLEngine
  File "/Users/pathXXXX/securitybot/securitybot/sql.py", line 7, in <module>
    from typing import Any, Sequence
ImportError: No module named typing`

**Comment by lfaraone** [comment]
Try `pip install typing`.

**Comment by hatityechindove** [comment]
👍 Had missed the `requirements.txt` file 😞
